/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piglatin;

/**
 *
 * @author nxxkxxk
 */
public class QA_Medium extends javax.swing.JFrame {

    /**
     * Creates new form Medium_QA
     */
    public QA_Medium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medAns = new javax.swing.JTextField();
        nxtBtn = new javax.swing.JButton();
        qMed = new javax.swing.JLabel();
        medBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medium Mode");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        medAns.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        medAns.setForeground(new java.awt.Color(51, 0, 0));
        medAns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medAns.setText("Answer Here");
        medAns.setToolTipText("");
        medAns.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(medAns);
        medAns.setBounds(80, 326, 290, 60);

        nxtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Next.png"))); // NOI18N
        nxtBtn.setBorderPainted(false);
        nxtBtn.setContentAreaFilled(false);
        nxtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(nxtBtn);
        nxtBtn.setBounds(470, 409, 106, 60);

        qMed.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        qMed.setForeground(new java.awt.Color(51, 0, 0));
        qMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qMed.setText("word");
        getContentPane().add(qMed);
        qMed.setBounds(185, 76, 230, 70);

        medBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Medium.png"))); // NOI18N
        getContentPane().add(medBG);
        medBG.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QA_Medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField medAns;
    private javax.swing.JLabel medBG;
    private javax.swing.JButton nxtBtn;
    private javax.swing.JLabel qMed;
    // End of variables declaration//GEN-END:variables
}
